//! MIPS64 Settings.

 use crate::settings::{self, detail, Builder};
 use core::fmt;
 
// Include code generated by `cranelift-codegen/meta/src/gen_settings.rs`. This file contains a
// public `Flags` struct with an impl for all of the settings defined in
// `cranelift-codegen/meta/src/isa/mips64/mod.rs`.
include!(concat!(env!("OUT_DIR"), "/settings-mips64.rs"));


